export const metadata = {
  title: "Pokemon App",
  description: "Generated by create next app",
};
import Navigation from "./components/Navigation";
import '@/app/style/main.css'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation/>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}